"""initial schema

Revision ID: 9f85a54fb16d
Revises: 
Create Date: 2026-08-29 18:51:23.446283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f85a54fb16d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('semester', sa.String(length=64), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine')),
    sa.UniqueConstraint('department', 'version', name='uq_routine_department_version')
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.create_index('ix_routine_department_active', ['department', 'is_active'], unique=False)

    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('office_room', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher'))
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index('ix_teacher_department', ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_initial'), ['initial'], unique=True)

    op.create_table('class_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=16), nullable=False),
    sa.Column('time_slot', sa.String(length=32), nullable=False),
    sa.Column('room', sa.String(length=64), nullable=False),
    sa.Column('room_type', sa.String(length=32), nullable=False),
    sa.Column('course_code', sa.String(length=64), nullable=False),
    sa.Column('course_title', sa.String(length=255), nullable=True),
    sa.Column('teacher', sa.String(length=16), nullable=False),
    sa.Column('batch', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('is_lab', sa.Boolean(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('start_min', sa.Integer(), nullable=False),
    sa.Column('end_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name=op.f('fk_class_session_routine_id_routine'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_session'))
    )
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.create_index('ix_session_batch', ['routine_id', 'batch'], unique=False)
        batch_op.create_index('ix_session_day_slot', ['routine_id', 'day', 'time_slot'], unique=False)
        batch_op.create_index('ix_session_room_day_slot', ['routine_id', 'room', 'day', 'time_slot'], unique=False)
        batch_op.create_index('ix_session_teacher', ['routine_id', 'teacher'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.drop_index('ix_session_teacher')
        batch_op.drop_index('ix_session_room_day_slot')
        batch_op.drop_index('ix_session_day_slot')
        batch_op.drop_index('ix_session_batch')

    op.drop_table('class_session')
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_initial'))
        batch_op.drop_index('ix_teacher_department')

    op.drop_table('teacher')
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_index('ix_routine_department_active')

    op.drop_table('routine')
    # ### end Alembic commands ###
